export const QUERY_IDS = {
  healthMarker: "seed-marker-v1",
  listIncidents: "incident-list-v1",
  incident: "incident-v1",
  affectedVersions: "affected-versions-v1",
  blastRadius: "blast-radius-v1",
  exactPath: "exact-path-v1",
  hydrateNode: "hydrate-node-v1",
  hydrateEdge: "hydrate-edge-v1",
  serviceEvidence: "service-evidence-v1",
  nodeCounts: "seed-node-counts-v1",
  edgeCounts: "seed-edge-counts-v1",
  nodeIdentities: "seed-node-identities-v1",
  edgeIdentities: "seed-edge-identities-v1",
  removeSeedMarker: "remove-seed-marker-v1",
  smokeCreateNodes: "smoke-create-nodes-v1",
  smokeCreateEdge: "smoke-create-edge-v1",
  smokeMatch: "smoke-match-v1",
  smokeDelete: "smoke-delete-v1",
} as const;

export const QUERIES = {
  upsertOrganization: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Organization, n.key = row.key, n.name = row.name, n.fixture = row.fixture`,
  upsertService: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Service, n.key = row.key, n.name = row.name, n.owner = row.owner, n.criticality = row.criticality, n.fixture = row.fixture`,
  upsertRepository: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Repository, n.key = row.key, n.name = row.name, n.url = row.url, n.fixture = row.fixture`,
  upsertLockfile: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Lockfile, n.key = row.key, n.digest = row.digest, n.path = row.path, n.lockfile_version = row.lockfile_version, n.fixture = row.fixture`,
  upsertBuild: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Build, n.key = row.key, n.build_id = row.build_id, n.commit_sha = row.commit_sha, n.timestamp_iso = row.timestamp_iso, n.timestamp_ms = row.timestamp_ms, n.environment = row.environment, n.lockfile_digest = row.lockfile_digest, n.fixture = row.fixture`,
  upsertPackage: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Package, n.key = row.key, n.name = row.name, n.ecosystem = row.ecosystem, n.fixture = row.fixture`,
  upsertPackageVersion: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:PackageVersion, n.key = row.key, n.name = row.name, n.version = row.version, n.ecosystem = row.ecosystem, n.fixture = row.fixture`,
  upsertAdvisory: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Advisory, n.key = row.key, n.osv_id = row.osv_id, n.summary = row.summary, n.severity = row.severity, n.window_start_iso = row.window_start_iso, n.window_start_ms = row.window_start_ms, n.window_end_iso = row.window_end_iso, n.window_end_ms = row.window_end_ms, n.source_url = row.source_url, n.fixture = row.fixture`,
  upsertSeedRun: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:SeedRun, n.key = row.key, n.version = row.version, n.created_at_iso = row.created_at_iso, n.fixture = row.fixture`,
  upsertOwns: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:OWNS {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertProduces: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:PRODUCES {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertHasLockfile: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:HAS_LOCKFILE {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertDependsOn: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:DEPENDS_ON {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertResolves: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:RESOLVES {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertUses: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:USES {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertHasBuild: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:HAS_BUILD {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertVersionOf: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:VERSION_OF {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertAffects: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:AFFECTS {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  upsertSeeded: `UNWIND $rows AS row MATCH (s {id: row.source}), (d {id: row.target}) MERGE (s)-[r:SEEDED {id: row.id}]->(d) SET r.key = row.key, r.source_ref = row.source_ref, r.fixture = row.fixture`,
  listIncidents: `MATCH (a:Advisory) RETURN a.id AS id, a.osv_id AS osv_id, a.summary AS summary, a.severity AS severity, a.window_start_iso AS window_start_iso, a.window_end_iso AS window_end_iso, a.source_url AS source_url ORDER BY a.osv_id`,
  incident: `MATCH (a:Advisory {key: $advisory_key}) RETURN a.id AS id, a.osv_id AS osv_id, a.summary AS summary, a.severity AS severity, a.window_start_iso AS window_start_iso, a.window_end_iso AS window_end_iso, a.window_start_ms AS window_start_ms, a.window_end_ms AS window_end_ms, a.source_url AS source_url`,
  affectedVersions: `MATCH (a:Advisory {key: $advisory_key})-[:AFFECTS]->(v:PackageVersion) RETURN v.id AS version_id ORDER BY version_id`,
  reverseBlastPaths: `CALL algo.SSpaths({sourceNode: $source, relTypes: ['DEPENDS_ON'], relDirection: 'incoming', maxLen: 8, pathCount: 100, resultLimit: 500}) YIELD path RETURN path`,
  exactPath: `CALL algo.SPpaths({sourceNode: $affected, targetNode: $service, relTypes: ['DEPENDS_ON'], relDirection: 'incoming', maxLen: 8, pathCount: 5}) YIELD path, pathWeight, pathCost RETURN path, pathWeight, pathCost`,
  hydrateNode: `MATCH (n {id: $id}) RETURN n.id AS id, labels(n) AS labels, n.key AS key, n.name AS name, n.version AS version, n.source_ref AS source_ref`,
  hydrateEdge: `MATCH (s)-[r {id: $id}]->(d) RETURN r.id AS id, r.key AS key, type(r) AS type, s.id AS source, d.id AS target, r.source_ref AS source_ref`,
  serviceEvidence: `MATCH (r:Repository)-[:PRODUCES]->(s:Service {id: $service_id}) MATCH (r)-[:HAS_LOCKFILE]->(l:Lockfile) OPTIONAL MATCH (b:Build)-[:USES]->(l) RETURN s.id AS service_id, s.key AS service_key, s.name AS service_name, s.owner AS owner, s.criticality AS criticality, r.id AS repository_id, r.name AS repository_name, l.digest AS lockfile_digest, b.build_id AS build_id, b.timestamp_iso AS timestamp_iso, b.timestamp_ms AS timestamp_ms, b.environment AS environment, b.lockfile_digest AS build_lockfile_digest ORDER BY b.timestamp_ms`,
  services: `MATCH (s:Service) RETURN s.id AS id, s.key AS key, s.name AS name, s.owner AS owner, s.criticality AS criticality ORDER BY s.name`,
  seedMarker: `MATCH (s:SeedRun {key: 'seed:blastpath-demo-v1'})-[:SEEDED]->(o:Organization) RETURN s.key AS key, s.version AS version`,
  seedNodeCounts: `MATCH (n) RETURN labels(n) AS labels, count(n) AS count`,
  seedEdgeCounts: `MATCH (s)-[r]->(d) RETURN type(r) AS type, count(r) AS count`,
  seedNodeIdentities: `MATCH (n) RETURN n.id AS id ORDER BY id`,
  seedEdgeIdentities: `MATCH (s)-[r]->(d) RETURN r.id AS id ORDER BY id`,
  removeSeedMarker: `MATCH (s:SeedRun {key: 'seed:blastpath-demo-v1'}) DETACH DELETE s`,
  smokeCreateNodes: `UNWIND $rows AS row MERGE (n {id: row.id}) SET n:Smoke, n.key = row.key RETURN n.id AS id`,
  smokeCreateEdge: `MATCH (s {id: $source}), (d {id: $target}) MERGE (s)-[r:SMOKE_LINK {id: $id}]->(d) RETURN r.id AS id`,
  smokeMatch: `MATCH (s:Smoke)-[r:SMOKE_LINK]->(d:Smoke) RETURN d.id AS destination_id`,
  smokeDelete: `MATCH (n:Smoke) DETACH DELETE n`,
} as const;

export const NODE_QUERY_BY_LABEL = {
  Organization: QUERIES.upsertOrganization,
  Service: QUERIES.upsertService,
  Repository: QUERIES.upsertRepository,
  Lockfile: QUERIES.upsertLockfile,
  Build: QUERIES.upsertBuild,
  Package: QUERIES.upsertPackage,
  PackageVersion: QUERIES.upsertPackageVersion,
  Advisory: QUERIES.upsertAdvisory,
  SeedRun: QUERIES.upsertSeedRun,
} as const;

export const EDGE_QUERY_BY_TYPE = {
  OWNS: QUERIES.upsertOwns,
  PRODUCES: QUERIES.upsertProduces,
  HAS_LOCKFILE: QUERIES.upsertHasLockfile,
  DEPENDS_ON: QUERIES.upsertDependsOn,
  RESOLVES: QUERIES.upsertResolves,
  USES: QUERIES.upsertUses,
  HAS_BUILD: QUERIES.upsertHasBuild,
  VERSION_OF: QUERIES.upsertVersionOf,
  AFFECTS: QUERIES.upsertAffects,
  SEEDED: QUERIES.upsertSeeded,
} as const;
